spring:
  application:
    name: server
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${MYSQL_DATABASE:fashion_e_commerce}
    url: ${spring.datasource.url}
    locations: classpath:db/migration
  jackson:
    mapper:
      sort-properties-alphabetically: false

application:
  white-list:
    - /v1/auth/login
    - /v1/auth/register
    - /v1/auth/logout
    - /v1/auth/verify
    - /v1/auth/resend-verify
    - /v1/auth/reset-password/**
    - /v1/auth/renew-access-token
    - /greeting
server:
  servlet:
    context-path: /fashion-e-commerce
  port: 8080
